name: 'Go Check Dependency'
description: 'Check Go dependency vulnerability using OWASP tool'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --enableExperimental
    - --format
    - ALL
    - --project
    - GolangOWASPExample
    - --scan
    - .
    - --out
    - ./reports
