name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-dependency:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Go Check Dependency OWASP
      id: OWASP
      uses: ./.github/actions/check-dependency
    - name: Publish artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: owasp-depdendency-report
        path: reports
        retention-days: 5
